import { Router } from 'express';
import { z } from 'zod';
import { inventoryRepository } from './inventory.repository.js';
import { asyncHandler } from '../../utils/asyncHandler.js';
import { success } from '../../utils/apiResponse.js';
import { validate } from '../../middleware/validation.middleware.js';
import { authenticate } from '../../middleware/auth.middleware.js';
import { resolveTenantFromAuth } from '../../middleware/tenant.middleware.js';
import { authorize, requireStaff } from '../../middleware/authorize.middleware.js';
export const inventoryRoutes = Router();
inventoryRoutes.use(authenticate, resolveTenantFromAuth);
inventoryRoutes.get('/:productId', asyncHandler(async (req, res) => success(res, await inventoryRepository.get(req.params.productId, req.tenant.id))));
inventoryRoutes.post('/:productId/adjust', authorize('inventory.adjust'), requireStaff, validate(z.object({ delta: z.coerce.number().int().refine((value) => value !== 0), reason: z.string().trim().min(2).max(255) })), asyncHandler(async (req, res) => success(res, await inventoryRepository.adjust({ productId: req.params.productId, tenantId: req.tenant.id, ...req.body }))));
