import { Router } from 'express';
import { authRoutes } from './modules/auth/auth.routes.js';
import { catalogRoutes } from './modules/catalog/catalog.routes.js';
import { inventoryRoutes } from './modules/inventory/inventory.routes.js';
import { tenantRoutes } from './modules/tenants/tenant.routes.js';
import { domainRoutes } from './modules/domains/domain.routes.js';
import { cartRoutes } from './modules/cart/cart.routes.js';
import { orderRoutes } from './modules/orders/order.routes.js';
import { paymentRoutes } from './modules/payments/payment.routes.js';
import { shippingRoutes } from './modules/shipping/shipping.routes.js';
import { returnRoutes } from './modules/returns-refunds/return.routes.js';
import { promotionRoutes } from './modules/promotions/promotion.routes.js';
import { settingsRoutes } from './modules/settings/settings.routes.js';
import { cmsRoutes } from './modules/cms/cms.routes.js';
import { mediaRoutes } from './modules/media/media.routes.js';
import { customerRoutes } from './modules/customers/customer.routes.js';
import { notificationRoutes } from './modules/notifications/notification.routes.js';
import { taxRoutes } from './modules/tax/tax.routes.js';
import { analyticsRoutes } from './modules/analytics/analytics.routes.js';
import { reportRoutes } from './modules/reports/report.routes.js';
import { auditRoutes } from './modules/audit-logs/audit.routes.js';
import { platformRoutes } from './modules/platform/platform.routes.js';
import { roleRoutes } from './modules/roles-permissions/role.routes.js';
import { wishlistRoutes } from './modules/wishlist/wishlist.routes.js';
import { reviewRoutes } from './modules/reviews/review.routes.js';
import { blogRoutes } from './modules/blog/blog.routes.js';
import { adminOrderRoutes } from './modules/orders/admin-order.routes.js';
import { catalogManagementRoutes } from './modules/catalog/catalog-management.routes.js';
import { catalogPublicRoutes } from './modules/catalog/catalog-public.routes.js';
import { warehouseRoutes } from './modules/inventory/warehouse.routes.js';

export const routes = Router();
routes.use('/auth', authRoutes);
routes.use('/tenants', tenantRoutes);
routes.use('/domains', domainRoutes);
routes.use('/catalog/public', catalogPublicRoutes);
routes.use('/catalog', catalogRoutes);
routes.use('/catalog', catalogManagementRoutes);
// `warehouseRoutes` (/inventory/warehouses/...) must be mounted before
// `inventoryRoutes` (/inventory/:productId) — otherwise "warehouses" is
// swallowed as a :productId and the warehouse endpoints are unreachable.
routes.use('/inventory', warehouseRoutes);
routes.use('/inventory', inventoryRoutes);
routes.use('/cart', cartRoutes);
routes.use('/orders', orderRoutes);
routes.use('/admin/orders', adminOrderRoutes);
routes.use('/payments', paymentRoutes);
routes.use('/shipping', shippingRoutes);
routes.use('/returns', returnRoutes);
routes.use('/promotions', promotionRoutes);
routes.use('/settings', settingsRoutes);
routes.use('/cms', cmsRoutes);
routes.use('/media', mediaRoutes);
routes.use('/customers', customerRoutes);
routes.use('/notifications', notificationRoutes);
routes.use('/tax', taxRoutes);
routes.use('/analytics', analyticsRoutes);
routes.use('/reports', reportRoutes);
routes.use('/audit-logs', auditRoutes);
routes.use('/platform', platformRoutes);
routes.use('/roles', roleRoutes);
routes.use('/wishlist', wishlistRoutes);
routes.use('/reviews', reviewRoutes);
routes.use('/blog', blogRoutes);
