import { withTransaction } from '../../database/connection.js';
import { paymentRepository } from './payment.repository.js';
import { CodGateway } from './payment.gateway.js';
import { AppError, assertFound } from '../../utils/errors.js';

const codGateway = new CodGateway();
export const paymentService = {
  async get(id, tenantId, userId) { return assertFound(await paymentRepository.find(id, tenantId, userId), 'Payment not found'); },
  async confirm(id, tenantId, userId) { return withTransaction(async (connection) => { const payment = assertFound(await paymentRepository.lock(id, tenantId, userId, connection), 'Payment not found'); if (payment.status === 'PAID') return payment; if (payment.method !== 'COD') throw new AppError('External payment confirmation must come from a verified provider webhook', 409, 'PAYMENT_VERIFICATION_REQUIRED'); if (payment.status !== 'PENDING') throw new AppError('Payment cannot be confirmed in its current state', 409, 'PAYMENT_ALREADY_PROCESSED'); await codGateway.createPayment({ amount: payment.amount }); await paymentRepository.setStatus(id, tenantId, userId, 'PENDING', 'PAID', connection); await paymentRepository.setOrderStatus(payment.orderId, tenantId, userId, 'PAYMENT_PENDING', 'PAID', connection); return paymentRepository.find(id, tenantId, userId, connection); }); },
  async refund(id, tenantId, userId, amount, options = {}) { return withTransaction(async (connection) => { const payment = assertFound(options.staff ? await paymentRepository.lockForStaff(id, tenantId, connection) : await paymentRepository.lock(id, tenantId, userId, connection), 'Payment not found'); const refundable = Number(payment.amount) - Number(payment.refundedAmount); if (payment.status !== 'PAID' && payment.status !== 'PARTIALLY_REFUNDED') throw new AppError('Payment is not refundable', 409, 'PAYMENT_NOT_REFUNDABLE'); if (amount <= 0 || amount > refundable) throw new AppError('Refund amount exceeds refundable balance', 422, 'INVALID_REFUND_AMOUNT'); const nextStatus = amount === refundable ? 'REFUNDED' : 'PARTIALLY_REFUNDED'; if (options.staff) await paymentRepository.refundForStaff(id, tenantId, amount, nextStatus, connection); else await paymentRepository.refund(id, tenantId, userId, amount, nextStatus, connection); return options.staff ? paymentRepository.find(id, tenantId, payment.userId, connection) : paymentRepository.find(id, tenantId, userId, connection); }); }
};
