import { Router } from 'express';
import { z } from 'zod';
import { authenticate } from '../../middleware/auth.middleware.js';
import { resolveTenantFromAuth } from '../../middleware/tenant.middleware.js';
import { requireStaff } from '../../middleware/authorize.middleware.js';
import { validate } from '../../middleware/validation.middleware.js';
import { asyncHandler } from '../../utils/asyncHandler.js';
import { success } from '../../utils/apiResponse.js';
import { AppError } from '../../utils/errors.js';
import { catalogManagementRepository as repository } from './catalog-management.repository.js';
const nameSlug = z.object({ name: z.string().min(2).max(160), slug: z.string().regex(/^[a-z0-9-]+$/).max(160) });
const category = nameSlug.extend({ parentId: z.coerce.number().int().positive().nullable().optional(), active: z.boolean().optional() });
const variant = z.object({ sku: z.string().min(1).max(80), barcode: z.string().max(80).optional(), price: z.coerce.number().nonnegative(), salePrice: z.coerce.number().nonnegative().nullable().optional(), weight: z.coerce.number().nonnegative().nullable().optional(), attributes: z.record(z.unknown()).optional() });
export const catalogManagementRoutes = Router();
catalogManagementRoutes.use(authenticate, resolveTenantFromAuth, requireStaff);
catalogManagementRoutes.get('/categories', asyncHandler(async (req, res) => success(res, await repository.categories(req.tenant.id))));
catalogManagementRoutes.post('/categories', validate(category), asyncHandler(async (req, res) => success(res, await repository.createCategory(req.body, req.tenant.id), 201)));
catalogManagementRoutes.get('/categories/:id', asyncHandler(async (req, res) => success(res, await repository.category(req.params.id, req.tenant.id))));
catalogManagementRoutes.patch('/categories/:id', validate(category.extend({ version: z.coerce.number().int().nonnegative() })), asyncHandler(async (req, res) => success(res, await repository.updateCategory(req.params.id, req.body, req.tenant.id))));
catalogManagementRoutes.delete('/categories/:id', asyncHandler(async (req, res) => { if (!(await repository.deleteCategory(req.params.id, req.tenant.id))) throw new AppError('Category has children or was not found', 409, 'CATEGORY_NOT_DELETABLE'); return success(res, null); }));
catalogManagementRoutes.get('/brands', asyncHandler(async (req, res) => success(res, await repository.brands(req.tenant.id))));
catalogManagementRoutes.post('/brands', validate(nameSlug), asyncHandler(async (req, res) => success(res, await repository.createBrand(req.body, req.tenant.id), 201)));
catalogManagementRoutes.patch('/brands/:id', validate(nameSlug.extend({ active: z.boolean().optional() })), asyncHandler(async (req, res) => success(res, await repository.updateBrand(req.params.id, req.body, req.tenant.id))));
catalogManagementRoutes.delete('/brands/:id', asyncHandler(async (req, res) => success(res, await repository.deleteBrand(req.params.id, req.tenant.id))));
catalogManagementRoutes.get('/attributes', asyncHandler(async (req, res) => success(res, await repository.attributes(req.tenant.id))));
catalogManagementRoutes.post('/attributes', validate(z.object({ name: z.string().min(2).max(80) })), asyncHandler(async (req, res) => success(res, await repository.createAttribute(req.body.name, req.tenant.id), 201)));
catalogManagementRoutes.get('/products/:productId/variants', asyncHandler(async (req, res) => success(res, await repository.variants(req.params.productId, req.tenant.id))));
catalogManagementRoutes.post('/products/:productId/variants', validate(variant), asyncHandler(async (req, res) => success(res, await repository.createVariant(req.params.productId, req.body, req.tenant.id), 201)));
catalogManagementRoutes.delete('/variants/:id', asyncHandler(async (req, res) => success(res, await repository.deleteVariant(req.params.id, req.tenant.id))));
catalogManagementRoutes.get('/products/:productId/images', asyncHandler(async (req, res) => success(res, await repository.images(req.params.productId, req.tenant.id))));
catalogManagementRoutes.post('/products/:productId/images', validate(z.object({ imageUrl: z.string().url().max(1000), mediaId: z.coerce.number().int().positive().optional(), variantId: z.coerce.number().int().positive().optional(), altText: z.string().max(255).optional(), sortOrder: z.coerce.number().int().nonnegative().optional(), isPrimary: z.boolean().optional() })), asyncHandler(async (req, res) => success(res, await repository.addImage(req.params.productId, req.body, req.tenant.id), 201)));
catalogManagementRoutes.delete('/images/:id', asyncHandler(async (req, res) => success(res, await repository.deleteImage(req.params.id, req.tenant.id))));
